SELECT * FROM roles

INSERT INTO roles (id, name) VALUES (1, 'USER') ON DUPLICATE KEY UPDATE name='USER';
INSERT INTO roles (id, name) VALUES (2, 'MODERATOR') ON DUPLICATE KEY UPDATE name='MODERATOR';
INSERT INTO roles (id, name) VALUES (3, 'ADMIN') ON DUPLICATE KEY UPDATE name='ADMIN';
